### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by MuhammadBayiz** [WaleedMortaja/RtlSubtitleCorrector#1]
Hi! I'm trying to run this script in Termux Android Terminal using openjdk-17 but i get this error, after some googling around it seems that the classpath is either wrong or not specified in the Manifest, maybe? Cold you help with this, thanks

**Comment by MuhammadBayiz** [comment]
Wrong jar execution, execute the script type
`java -jar RtlSubtitleCorrector.jar my_subtitle.srt`

However the REGEX pattern is wrong in this script it matches the timing of the subtitle lines and adds RTL Unicode character to it

**Comment by WaleedMortaja** [comment]
@MuhammadBayiz on Linux, you may need to make the file executable using `chmod u+x RtlSubtitleCorrector.jar` before running it as `./RtlSubtitleCorrector.jar`.
If It still does not work, or the regex still matches timing, please re-open this issue, and attach your subtitle file.

**Comment by MuhammadBayiz** [comment]
You're right i wasn't correctly run the script thanks for the clarification
